### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Seriusam** [brunocvcunha/instagram4j#124]
**I get the following error when I try to login with,** 

```
Instagram4j instagram = Instagram4j.builder().username("").password("").build();
        instagram.setup();
        instagram.login();
```
**I get,** 

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/client/CookieStore
	at test1.NewClass.main(NewClass.java:12)
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.CookieStore
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
C:\Users\fatih\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 0 seconds)
```

**Comment by Seriusam** [comment]
The problem seems to be with the CookieStore Class. Any chance you were using **import java.net.CookieStore;**, But forgot updating it in the library?

**Comment by brunocvcunha** [comment]
@Seriusam how are you using it / managing the dependencies? Instagram4j depends on a bunch of libraries, so I suggest you to use Maven or Gradle to manage it properly.
