### ISSUE TITLE
Posting to story: Failed to configure image: Unknown Server Error.

### ISSUE THREAD

**Issue by Aulig** [brunocvcunha/instagram4j#185]
Hey, Im trying to post an image to my story with the following code:

`                instagram.sendRequest(new InstagramUploadStoryPhotoRequest(f));
`
I make sure that the image is in 9:16 ratio as required by instagram beforehand. When executing i get this exception:

> java.lang.IllegalArgumentException: Failed to configure image: Unknown Server Error.
	at org.brunocvcunha.instagram4j.requests.InstagramUploadStoryPhotoRequest.execute(InstagramUploadStoryPhotoRequest.java:106)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadStoryPhotoRequest.execute(InstagramUploadStoryPhotoRequest.java:46)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:285)

**Comment by jvogit** [comment]
@Aulig 

Thanks for the issue. I have already come up with a resolution. Will post a pull request soon. You can use the updated request when the pull request is created for your project.

It seems the fields client_shared_at and client_timetamp are causing the problems. You may remove it from the request and it will work just fine.

**Comment by Aulig** [comment]
Oh nice, thanks for the quick response!
