### ISSUE TITLE
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException

### ISSUE THREAD

**Issue by spritrl** [brunocvcunha/instagram4j#189]
Idk this error: 
```
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<!DOCTYPE html>
<html lang="en" id="facebook">
  <head>
    <title>Facebook | Error</title>
    <meta charset="utf-8">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="cache-control" content="no-store">
    <meta http-equiv="cache-control" content="max-age=0">
    <meta http-equiv="expires" content="-1">
    <meta http-equiv="pragma" content="no-cache">
    <meta name="robots" content="noindex,nofollow">
    <style>
      html, body {
        color: #141823;
       "[truncated 2459 chars]; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1892)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4129)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:139)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:111)
	at org.brunocvcunha.instagram4j.requests.InstagramUserFeedRequest.parseResult(InstagramUserFeedRequest.java:49)
	at org.brunocvcunha.instagram4j.requests.InstagramUserFeedRequest.parseResult(InstagramUserFeedRequest.java:31)
	at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:56)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:228)
	at com.ghost.main.Main.main(Main.java:158)

```

**Comment by brunocvcunha** [comment]
What were you doing? Code?

**Comment by AndreaCioccarelli** [comment]
You cannot parse with a JSON parser an html page

**Comment by AndreaCioccarelli** [comment]
You cannot parse with a JSON parser an html page

**Comment by Sibiya-Varghese** [comment]
same error..some one clear it
