### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ElDzi** [brunocvcunha/instagram4j#20]
Exception in thread "main" org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 510978; received: 497724
My code:
`    System.out.println("PODAJ TAG");
    String tag = s.nextLine();
    InstagramFeedResult tagFeed =  insta.sendRequest(new InstagramTagFeedRequest(tag));

    System.out.println("WYSZUKANO " + tagFeed.getItems().size() + " zdjec");
    for (InstagramFeedItem k : tagFeed.getItems())
            insta.sendRequest(new InstagramLikeRequest(k.getPk()));

`
I'm logged.
Logs:
`PODAJ TAG
cleant
2017-06-07 09:30:10 [main] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.InstagramTagFeedRequest
Exception in thread "main" org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 510978; received: 497724
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:247)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:291)
	at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:52)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:202)
	at pl.eldzi.insta.Main.main(Main.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1
`

**Comment by brunocvcunha** [comment]
Hi @ElDzi 

Does it happen every time? It looks like some networking glitch.

**Comment by ElDzi** [comment]
Yes, everytime ;c

**Comment by brunocvcunha** [comment]
Worked fine for me.

If you're running too many requests, I suggest including some intervals/sleep between requests. Maybe the server is canceling the requests in-flight.
