### ISSUE TITLE
Error while getting all followers of a public profile

### ISSUE THREAD

**Issue by jcagz-iscteiul** [brunocvcunha/instagram4j#246]
Hi everyone, i'm trying to get every followers username of a publicprofile with more than 200k followers, but im getting the following error after some minutes:

`Exception in thread "main" java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:198)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.Reader.read(Unknown Source)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:247)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:291)
	at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:52)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:277)`

im using the following code to do that

`
List users = new ArrayList();
String nextMaxId = null;
while (true) {
InstagramGetUserFollowersResult fr = instagram.sendRequest(new InstagramGetUserFollowersRequest(primary_key, nextMaxId));

    	if(fr.getUsers().equals(null))
    		break;
    	for(int i = 0; i < fr.getUsers().size(); i++) {
    		System.out.println(i + fr.getUsers().get(i).username + "-" + fr.getUsers().get(i).pk);
    	}
    	nextMaxId = fr.getNext_max_id();
    	if (nextMaxId == null) {
    		break;
    	}
    }`

Do you know how i can lead with this exception?

**Comment by jcagz-iscteiul** [comment]
@brunocvcunha you can close this issue, i already noticed how to do it. Thank you for this API

**Comment by imjd175** [comment]
@jcagz-iscteiul Could you tell me how to do it?

**Comment by JoaoGarcez** [comment]
> @jcagz-iscteiul Could you tell me how to do it?

`List<InstagramUserSummary> users = new ArrayList<InstagramUserSummary>();
String nextMaxId = null;
while (true) {
	InstagramGetUserFollowersResult fr = instagram.sendRequest(new InstagramGetUserFollowersRequest(userId, nextMaxId));
	users.addAll(fr.getUsers());
	nextMaxId = fr.getNext_max_id();
	if (nextMaxId == null) {
		break;
	}
}`

**Comment by bgokcol** [comment]
> > @jcagz-iscteiul Could you tell me how to do it?
> 
> List users = new ArrayList();
> String nextMaxId = null;
> while (true) {
> InstagramGetUserFollowersResult fr = instagram.sendRequest(new InstagramGetUserFollowersRequest(userId, nextMaxId));
> users.addAll(fr.getUsers());
> nextMaxId = fr.getNext_max_id();
> if (nextMaxId == null) {
> break;
> }
> }

I have 660 followers but users.size returns 512?

**Comment by HectorHumanes** [comment]
> I have 660 followers but users.size returns 512?

I'm having this issue too, I can't get all the followers I have. Maybe one page of the result is missing?
