### ISSUE TITLE
InvalidFormatException when log in

### ISSUE THREAD

**Issue by MuratKaragozgil** [brunocvcunha/instagram4j#260]
Hello, 

I have created a main method like this;

`Instagram4j instagram = Instagram4j.builder().username("someusername").password("somepassword").build();
        instagram.setup();
        InstagramLoginResult loginResult = instagram.login();
`

Then I got these exception. I can't handle it. 

`Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `long` from String "1953153203105626434_caption": not a valid Long value
 at [Source: (StringReader); line: 1, column: 5922] (through reference chain: org.brunocvcunha.instagram4j.requests.payload.InstagramFeedResult["items"]->java.util.ArrayList[1]->org.brunocvcunha.instagram4j.requests.payload.InstagramFeedItem["caption"]->org.brunocvcunha.instagram4j.requests.payload.InstagramComment["pk"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1549)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:911)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer._parseLong(NumberDeserializers.java:584)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:557)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:535)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:141)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:111)
	at org.brunocvcunha.instagram4j.requests.InstagramTimelineFeedRequest.parseResult(InstagramTimelineFeedRequest.java:58)
	at org.brunocvcunha.instagram4j.requests.InstagramTimelineFeedRequest.parseResult(InstagramTimelineFeedRequest.java:29)
	at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:56)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:275)
	at org.brunocvcunha.instagram4j.Instagram4j.emulateUserLoggedIn(Instagram4j.java:290)
	at org.brunocvcunha.instagram4j.Instagram4j.login(Instagram4j.java:205)
	at Main.main(Main.java:14)`

**Comment by tayfunyasar** [comment]
I'm having same exception.

> Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `long` from String "2022428630558696939_caption": not a valid Long value
>  at [Source: (StringReader); line: 1, column: 31527] (through reference chain: org.brunocvcunha.instagram4j.requests.payload.InstagramFeedResult["items"]->java.util.ArrayList[5]->org.brunocvcunha.instagram4j.requests.payload.InstagramFeedItem["caption"]->org.brunocvcunha.instagram4j.requests.payload.InstagramComment["pk"])
>
