### ISSUE TITLE
Lombok not found?

### ISSUE THREAD

**Issue by sh4d0000** [brunocvcunha/instagram4j#29]
```
Exception in thread "Timer-0" java.lang.NoClassDefFoundError: lombok/Lombok
        at org.brunocvcunha.instagram4j.requests.InstagramGetUserFollowingRequest.parseResult(InstagramGetUserFollowingRequest.java:50)
        at org.brunocvcunha.instagram4j.requests.InstagramGetUserFollowingRequest.parseResult(InstagramGetUserFollowingRequest.java:32)
        at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:56)
        at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:202)
        at org.brunocvcunha.instagram4j.Instagram4j$sendRequest$2.call(Unknown Source)

```

**Comment by krismorte** [comment]
What is the solution?
