### ISSUE TITLE
Cannot download followers

### ISSUE THREAD

**Issue by Athamax** [brunocvcunha/instagram4j#31]
Hi,

I'm trying to get the list of an account's followers.
InstagramGetUserFollowersRequest() only downloads 193 followers, out of more than 12k.
Is this a bug ? Can I do something to fix it?

**Comment by BondarenkoEvgeny** [comment]
No, this is not a bug.
Instagram returns the list of accounts by parts.

```
List<InstagramUserSummary> users = new ArrayList<InstagramUserSummary>();
String nextMaxId = null;
while (true) {
	InstagramGetUserFollowersResult fr = instagram.sendRequest(new InstagramGetUserFollowersRequest(userId, nextMaxId));
	users.addAll(fr.getUsers());
	nextMaxId = fr.getNext_max_id();
	if (nextMaxId == null) {
		break;
	}
}
```

**Comment by Athamax** [comment]
Thanks for the help @BondarenkoEvgeny , I tried that, but it just gives a Socket Exception at around 971 followers read:


```
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:198)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:247)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:291)
	at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:52)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:202)
	at jinstagram.InstagramRunner.main(InstagramRunner.java:81)
```

**Comment by BondarenkoEvgeny** [comment]
First, read this #19.

To minimize HTTP errors, configure httpclient.
Example:
```
int CONNECTION_TIMEOUT = 30 * 1000;
int SO_TIMEOUT = 30 * 1000;
boolean STALE_CONNECTION_CHECK = true;
boolean SO_KEEPALIVE = true;
int RETRY_COUNT = 5;

instagram.getClient().getParams().setParameter("http.socket.timeout", SO_TIMEOUT);
instagram.getClient().getParams().setParameter("http.connection.timeout", CONNECTION_TIMEOUT);
instagram.getClient().getParams().setParameter("http.connection.stalecheck", STALE_CONNECTION_CHECK);
instagram.getClient().getParams().setParameter("http.socket.keepalive", SO_KEEPALIVE);
instagram.getClient().getParams().setParameter("http.protocol.content-charset", "UTF-8");
instagram.getClient().setHttpRequestRetryHandler(new DefaultHttpRequestRetryHandler(RETRY_COUNT, true));
```

**Comment by brunocvcunha** [comment]
That. Thanks, @BondarenkoEvgeny.

I would suggest some reasonable sleep between the pagination requests like a normal user would do.

**Comment by tayfunyasar** [comment]
I have configured this.

It seems not working.

`	private Instagram4j getInstance() throws ClientProtocolException, IOException {
		if (InstagramServiceImpl.instagram == null) {
			InstagramServiceImpl.instagram = Instagram4j.builder().username(this.webConstants.getInstagramUsername())
					.password(this.webConstants.getInstagramPassword()).build();

			InstagramServiceImpl.instagram.setup();
			InstagramServiceImpl.instagram.login();

			int CONNECTION_TIMEOUT = 30 * 1000;
			int SO_TIMEOUT = 30 * 1000;
			boolean STALE_CONNECTION_CHECK = true;
			boolean SO_KEEPALIVE = true;
			int RETRY_COUNT = 5;

			instagram.getClient().getParams().setParameter("http.socket.timeout", SO_TIMEOUT);
			instagram.getClient().getParams().setParameter("http.connection.timeout", CONNECTION_TIMEOUT);
			instagram.getClient().getParams().setParameter("http.connection.stalecheck", STALE_CONNECTION_CHECK);
			instagram.getClient().getParams().setParameter("http.socket.keepalive", SO_KEEPALIVE);
			instagram.getClient().getParams().setParameter("http.protocol.content-charset", "UTF-8");
			instagram.getClient().setHttpRequestRetryHandler(new DefaultHttpRequestRetryHandler(RETRY_COUNT, true));
		}

		return InstagramServiceImpl.instagram;
	}`

**Comment by tayfunyasar** [comment]
Can you provide a permanent solution to fix this? 

You guys did randomWait() before. I think we need something like that.
