### ISSUE TITLE
Generate user's follower list: ConnectionClosedException

### ISSUE THREAD

**Issue by phoenixrising1800** [brunocvcunha/instagram4j#315]
I'm trying to generate an ArrayList of a user (with over 180k+ followers), and am using a paginated sendRequest - however, it seems to keep breaking after awhile and refuses to complete the generation. The program keeps terminating and reporting the following exception: 

**org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 88060; received: 39129**

	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:247)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:291)
	at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:52)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:277)
	at com.xxx.App.main(App.java:36)
`

Is it perhaps because I am sending too many requests? If so, how can I get around this?

**Comment by phoenixrising1800** [comment]
Never mind, I fixed it! For anyone else having this problem, I recommend putting the Thread to sleep for about 30sec-1min in between grabbing each amount of followers
