### ISSUE TITLE
Post Video Issue

### ISSUE THREAD

**Issue by DanielePancottini** [brunocvcunha/instagram4j#327]
Hi, I have a problem with the post video request, maybe related to a dependency.
Just for information, I'm using Ivy as dependency manager and eclipse as IDE.

The code is the following:

```
@POST
@Path("postVideo")
public Response uploadInstagramVideo() {
		
		
	File fileVideo = new File("/res/video1.mp4");
	System.err.println(fileVideo.canExecute());
	System.err.println(fileVideo.getAbsolutePath());
		
		
		
	try {
		instagram.setup();
		instagram.login();
			
		instagram.sendRequest(new InstagramUploadVideoRequest(fileVideo, "video prova bro"));
	      }
	catch(Exception e) {
		     System.err.println("Upload Instagram Video Exception: " + e);
		     return Response.serverError().entity("Upload Instagram Video Error with following exception: " + e).build();
		}
		
		return Response.ok().build();
	}
```
The exception is the following:
```
mag 28, 2019 9:23:54 PM org.apache.catalina.core.StandardWrapperValve invoke
GRAVE: Servlet.service() for servlet [it.programmatorihtml.autoinstagram.configuration.ApplicationConfig] in context with path [/AutogramService] threw exception [org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil] with root cause
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Loader.java:585)
	at org.bytedeco.javacpp.Loader.load(Loader.java:530)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2819)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:468)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:462)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.configureThumbnail(InstagramUploadVideoRequest.java:131)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:109)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:52)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:275)
	at it.programmatorihtml.autoinstagram.endpoints.InstagramResource.uploadInstagramVideo(InstagramResource.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)


```

**Comment by jemand771** [comment]
Can you please post your code and specifically say which line throws the error?

**Comment by DanielePancottini** [comment]
@jemand771 I've just published my code, and the line throws exception is the following: 

`instagram.sendRequest(new InstagramUploadVideoRequest(fileVideo, "video prova bro"));`

**Comment by jemand771** [comment]
Thank you. Just for other people reading this: I am getting a similar error, but my stacktrace is shorter (probably related to where the request is called from)

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:585)
	at org.bytedeco.javacpp.Loader.load(Loader.java:530)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2819)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:468)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:462)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.configureThumbnail(InstagramUploadVideoRequest.java:131)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:109)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:52)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:275)
	at net.jemand771.instagram4j.MyCodeTestClass.main(MyCodeTestClass.java:39)
```
I will have a look into your issue and comment when i've figured something out. I'm currently a bit busy so I might need a few days ;)

**Comment by DanielePancottini** [comment]
@jemand771 Perfect, so my problem is not alone, it's very strange. Maybe the problem is related to the "javacpp" dependency

**Comment by jemand771** [comment]
@DanielePancottini hi, it's me again.
You were right, it is a dependency issue. Try adding this dependency to your POM:
```
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv-platform</artifactId>
    <version>1.3.1</version>
</dependency>
```
This fixes it for me. If it works for you aswell, I'll open a PR for it.

**Comment by DanielePancottini** [comment]
Perfect, thank you. I will try tomorrow and then I will let you know

**Comment by DanielePancottini** [comment]
@jemand771 Ok, the problem seems to be fixed, you can proceed with PR, thanks 👍
