### ISSUE TITLE
No support for arm-64?

### ISSUE THREAD

**Issue by Anchorer** [brunocvcunha/instagram4j#35]
Hi, I have a device with 64-bit CPU. When I run the instagram4j API, I get this issue: 

```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/log4j/Logger;
    at org.brunocvcunha.instagram4j.Instagram4j.<clinit>(Instagram4j.java:54)
    at org.brunocvcunha.instagram4j.Instagram4j.builder(Instagram4j.java:91)
    at me.godap.followers.component.InstagramManager.login(InstagramManager.java:38)
    at me.godap.followers.activity.MainActivity.onClick(MainActivity.java:45)
    at android.view.View.performClick(View.java:5669)
    at android.view.View$PerformClick.run(View.java:22540)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6334)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.log4j.Logger" on path: DexPathList[[zip file "/data/app/me.godap.followers-1/base.apk"],nativeLibraryDirectories=[/data/app/me.godap.followers-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.brunocvcunha.instagram4j.Instagram4j.<clinit>(Instagram4j.java:54) 
        at org.brunocvcunha.instagram4j.Instagram4j.builder(Instagram4j.java:91) 
        at me.godap.followers.component.InstagramManager.login(InstagramManager.java:38) 
        at me.godap.followers.activity.MainActivity.onClick(MainActivity.java:45) 
        at android.view.View.performClick(View.java:5669) 
        at android.view.View$PerformClick.run(View.java:22540) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6334) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

Is there no support for arm-64 CPU? Can you fix this issue please? Thanks.

**Comment by brunocvcunha** [comment]
I didn't look into compatibility details yet.
There's the issue #5 that @charlieAndroidDev was able to make it work on Android, try to take a look there

**Comment by Anchorer** [comment]
@brunocvcunha 
Thanks. I tried the method by [@charlieAndroidDev](https://github.com/charlieandroiddev) and it works.

**Comment by brunocvcunha** [comment]
Closing this for now.
