### ISSUE TITLE
NoSuchMethodError 

### ISSUE THREAD

**Issue by ussernamenikita** [brunocvcunha/instagram4j#50]
Fail with this error.
Output : 
```2017-08-24 20:16:27 [main ] INFO org.brunocvcunha.instagram4j.Instagram4j - Setup...
2017-08-24 20:16:27 [main ] INFO org.brunocvcunha.instagram4j.Instagram4j - Device ID is: android-d47b794215521eb9, random id: f69dfdc0-88ef-11e7-a181-4ccc6a626166
2017-08-24 20:16:27 [main ] INFO org.brunocvcunha.instagram4j.Instagram4j - Logging with user nikitabulygin5436 and password *********************
2017-08-24 20:16:27 [main ] INFO org.brunocvcunha.instagram4j.Instagram4j - Sending request: org.brunocvcunha.instagram4j.requests.internal.InstagramFetchHeadersRequest
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.NoSuchMethodError: org.apache.http.impl.client.DefaultHttpClient.execute(Lorg/apache/http/client/methods/HttpUriRequest;)Lorg/apache/http/client/methods/CloseableHttpResponse;
	at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:48)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:202)
	at org.brunocvcunha.instagram4j.Instagram4j.getOrFetchCsrf(Instagram4j.java:175)
	at org.brunocvcunha.instagram4j.Instagram4j.login(Instagram4j.java:139)
	at rootprog.SceneSwitcher.getSharedInstagram(SceneSwitcher.java:589)
	at rootprog.SceneSwitcher.<init>(SceneSwitcher.java:501)
	at rootprog.SceneSwitcher.<clinit>(SceneSwitcher.java:98)
	at Main.main(Main.java:37)
	... 11 more
Exception running application Main
Disconnected from the target VM, address: '127.0.0.1:59437', transport: 'socket'

Process finished with exit code 1
```
Version 1.4

**Comment by brunocvcunha** [comment]
How did you generate the JAR to run? Are you including all Maven dependencies?
If you want this to work with Android, there's another issue in this repo that has some explanation on how to do it.

**Comment by brunocvcunha** [comment]
Closing. Check #5.

**Comment by ussernamenikita** [comment]
Hi, sorry but problem is not solved. I use maven library. The program is not for android. I was running project in debug mode, and error appears in InstagramGetRequest.java:31. 
I do not understand why it's happened. May be instagram4j use another http library in runtime ?
